services:
  web-app:
    image: web-app-prod:latest
    container_name: web-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
    depends_on:
      - json-api

  json-api:
    image: node:alpine
    container_name: json-container
    working_dir: /app
    volumes:
      # Usamos la ruta absoluta de tu EC2 para que no falle
      - /home/ec2-user/src/data:/app/data
    ports:
      - "3000:3000"
    command: sh -c "npm install -g json-server@0.17.4 && json-server --watch /app/data/db.json --host 0.0.0.0 --port 3000"
    restart: always
