services:
  web-app:
    image: web-app-prod:latest
    container_name: web-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mapeamos la carpeta de certificados de la EC2 al contenedor
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
